name: Gradle Build
on: [push, pull_request, release]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Gradle
      run: gradle build

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: All files
        path: /*
